/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    about: About;
    servicesPage: ServicesPage;
    gallery: Gallery;
    contact: Contact;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    servicesPage: ServicesPageSelect<false> | ServicesPageSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Usado no URL e na identificação interna.
   */
  slug: string;
  description: string;
  /**
   * Texto que entra na mensagem pronta do WhatsApp, por exemplo «remodelação de cozinha».
   */
  whatsappLabel: string;
  /**
   * Se vazio, usa o título. Aparece no select de Contacto quando «No formulário» está activo.
   */
  contactLabel?: string | null;
  featured?: boolean | null;
  inContactForm?: boolean | null;
  inFooter?: boolean | null;
  image?: (number | null) | Media;
  /**
   * Usado só se a imagem Media estiver vazia. Preferir o carregamento acima.
   */
  imageUrl?: string | null;
  imageAlt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  category?: ('Obras' | 'Remodelações' | 'Reabilitação' | 'Arquitetura' | 'Processo') | null;
  publishedAt?: string | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  whatsappLabel?: T;
  contactLabel?: T;
  featured?: T;
  inContactForm?: T;
  inFooter?: T;
  image?: T;
  imageUrl?: T;
  imageAlt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  publishedAt?: T;
  cover?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identidade, menu, hero, método, cobertura, FAQ e rodapé. A ordem do menu deve seguir a ordem das secções na homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  legalName: string;
  tagline: string;
  seoDescription?: string | null;
  whatsappE164: string;
  whatsappDisplay: string;
  phoneDisplay: string;
  phoneTel: string;
  contactEmail: string;
  /**
   * Destino do logótipo na secção Serviços, do rodapé e do redirecionamento de /reparacoes.
   */
  nexoServicesUrl: string;
  nexoServicesLabel?: string | null;
  whatsappCta: string;
  whatsappIntro: string;
  /**
   * A ordem aqui é a ordem no header. Deve coincidir com a ordem das secções na homepage.
   */
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  heroHeading: string;
  heroHeadingHighlight?: string | null;
  heroLede: string;
  heroSecondaryCta: string;
  heroSecondaryHref: string;
  heroSlides?:
    | {
        image?: (number | null) | Media;
        /**
         * Usado só se a imagem Media estiver vazia. Preferir o carregamento acima.
         */
        src?: string | null;
        alt: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  methodHeading: string;
  methodPhoto?: (number | null) | Media;
  /**
   * Usado só se a imagem Media estiver vazia. Preferir o carregamento acima.
   */
  methodPhotoUrl?: string | null;
  methodPhotoAlt?: string | null;
  methodSteps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  coverageHeading: string;
  coverageHighlight?: string | null;
  coverageSubheading?: string | null;
  coverageSubheadingHighlight?: string | null;
  coverageBody: string;
  coverageRegions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  coverageMapLabel: string;
  coverageMapsCta: string;
  mapsEmbedUrl?: string | null;
  mapsLink?: string | null;
  blogHeading?: string | null;
  blogHeadingHighlight?: string | null;
  blogIntro?: string | null;
  blogAllCta?: string | null;
  blogReadCta?: string | null;
  blogEmptyTitle?: string | null;
  blogEmptyBody?: string | null;
  blogEmptyAside?: string | null;
  blogEmptyCta?: string | null;
  blogPageIntro?: string | null;
  blogPageEmptyTitle?: string | null;
  blogPageEmptyBody?: string | null;
  blogPageEmptyAside?: string | null;
  faqHeading: string;
  faqHeadingHighlight?: string | null;
  faqIntro: string;
  faqPolicyHeading: string;
  faqPolicyItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  faqWhatsappCta: string;
  footerIntro: string;
  footerGuarantees: string;
  footerGuaranteesCta: string;
  footerNexoLabel: string;
  locationLine: string;
  footerContactsHeading?: string | null;
  footerContactRequestLabel?: string | null;
  footerWhatsappPrefix?: string | null;
  footerPhonePrefix?: string | null;
  footerEmailPrefix?: string | null;
  footerBlogLabel?: string | null;
  footerServicesHeading?: string | null;
  footerRepairsLabel?: string | null;
  footerGuaranteesHeading?: string | null;
  footerCopyright?: string | null;
  /**
   * O ícone só aparece no rodapé se «Visível no rodapé» estiver activo e o URL estiver preenchido.
   */
  socialLinks?:
    | {
        network: 'instagram' | 'facebook' | 'linkedin' | 'youtube' | 'tiktok' | 'x' | 'pinterest';
        /**
         * URL completo, por exemplo https://www.instagram.com/projetonexo
         */
        url?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  termsHeading?: string | null;
  termsParagraphs?:
    | {
        text: string;
        linkHref?: string | null;
        linkLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Página /sobre: textos e fotografias. Carregar imagens em Media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heroEyebrow?: string | null;
  heading: string;
  headingHighlight?: string | null;
  heroLead?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Usado só se a imagem Media estiver vazia. Preferir o carregamento acima.
   */
  heroImageUrl?: string | null;
  heroImageAlt?: string | null;
  storyTitle?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Grelha ao lado da história. Preferir Media; o URL só serve se a imagem estiver vazia.
   */
  placeholders?:
    | {
        label: string;
        image?: (number | null) | Media;
        /**
         * Usado só se a imagem Media estiver vazia. Preferir o carregamento acima.
         */
        imageUrl?: string | null;
        alt?: string | null;
        shape?: ('wide' | 'round' | 'square') | null;
        id?: string | null;
      }[]
    | null;
  valuesEyebrow?: string | null;
  valuesTitle?: string | null;
  valuesIntro?: string | null;
  values?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaBody?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  ctaWhatsappLabel?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos da secção Serviços. Os cartões em destaque vêm do catálogo, com «Em destaque na homepage».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage".
 */
export interface ServicesPage {
  id: number;
  heading: string;
  intro: string;
  contactLinkLabel: string;
  cardCta: string;
  nexoKicker: string;
  nexoHeading: string;
  nexoBody: string;
  nexoCta: string;
  serviceWhatsappCta?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos e fotografias da galeria na homepage e em /galeria. Carregar imagens em Media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  heading: string;
  intro?: string | null;
  environmentsHeading?: string | null;
  environmentsIntro?: string | null;
  contactCta?: string | null;
  mosaicContact?: {
    title?: string | null;
    body?: string | null;
    cta?: string | null;
    href?: string | null;
  };
  mosaicWork?: {
    title?: string | null;
    cta?: string | null;
    href?: string | null;
    fallbackTitle?: string | null;
    fallbackBody?: string | null;
    fallbackCta?: string | null;
  };
  projects?:
    | {
        title: string;
        titleLines?:
          | {
              line: string;
              id?: string | null;
            }[]
          | null;
        caption: string;
        isRealWork?: boolean | null;
        image?: (number | null) | Media;
        /**
         * Usado só se a imagem Media estiver vazia. Preferir o carregamento acima.
         */
        imageUrl?: string | null;
        alt: string;
        width?: number | null;
        height?: number | null;
        fit?: ('cover' | 'contain') | null;
        /**
         * Só para obra real. Cada passo é uma fotografia.
         */
        panels?:
          | {
              image?: (number | null) | Media;
              /**
               * Usado só se a imagem Media estiver vazia. Preferir o carregamento acima.
               */
              src?: string | null;
              alt: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textos da secção Contacto e do formulário.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading: string;
  body: string;
  otherServiceOption?: string | null;
  submitLabel: string;
  submittingLabel: string;
  successMessage: string;
  consent: string;
  nameLabel: string;
  phoneLabel: string;
  phoneHint?: string | null;
  emailLabel: string;
  emailHint?: string | null;
  serviceLabel: string;
  messageLabel: string;
  namePlaceholder?: string | null;
  phonePlaceholder?: string | null;
  emailPlaceholder?: string | null;
  servicePlaceholder?: string | null;
  messagePlaceholder?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  seoDescription?: T;
  whatsappE164?: T;
  whatsappDisplay?: T;
  phoneDisplay?: T;
  phoneTel?: T;
  contactEmail?: T;
  nexoServicesUrl?: T;
  nexoServicesLabel?: T;
  whatsappCta?: T;
  whatsappIntro?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  heroHeading?: T;
  heroHeadingHighlight?: T;
  heroLede?: T;
  heroSecondaryCta?: T;
  heroSecondaryHref?: T;
  heroSlides?:
    | T
    | {
        image?: T;
        src?: T;
        alt?: T;
        label?: T;
        id?: T;
      };
  methodHeading?: T;
  methodPhoto?: T;
  methodPhotoUrl?: T;
  methodPhotoAlt?: T;
  methodSteps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  coverageHeading?: T;
  coverageHighlight?: T;
  coverageSubheading?: T;
  coverageSubheadingHighlight?: T;
  coverageBody?: T;
  coverageRegions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  coverageMapLabel?: T;
  coverageMapsCta?: T;
  mapsEmbedUrl?: T;
  mapsLink?: T;
  blogHeading?: T;
  blogHeadingHighlight?: T;
  blogIntro?: T;
  blogAllCta?: T;
  blogReadCta?: T;
  blogEmptyTitle?: T;
  blogEmptyBody?: T;
  blogEmptyAside?: T;
  blogEmptyCta?: T;
  blogPageIntro?: T;
  blogPageEmptyTitle?: T;
  blogPageEmptyBody?: T;
  blogPageEmptyAside?: T;
  faqHeading?: T;
  faqHeadingHighlight?: T;
  faqIntro?: T;
  faqPolicyHeading?: T;
  faqPolicyItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  faqWhatsappCta?: T;
  footerIntro?: T;
  footerGuarantees?: T;
  footerGuaranteesCta?: T;
  footerNexoLabel?: T;
  locationLine?: T;
  footerContactsHeading?: T;
  footerContactRequestLabel?: T;
  footerWhatsappPrefix?: T;
  footerPhonePrefix?: T;
  footerEmailPrefix?: T;
  footerBlogLabel?: T;
  footerServicesHeading?: T;
  footerRepairsLabel?: T;
  footerGuaranteesHeading?: T;
  footerCopyright?: T;
  socialLinks?:
    | T
    | {
        network?: T;
        url?: T;
        enabled?: T;
        id?: T;
      };
  termsHeading?: T;
  termsParagraphs?:
    | T
    | {
        text?: T;
        linkHref?: T;
        linkLabel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heading?: T;
  headingHighlight?: T;
  heroLead?: T;
  heroImage?: T;
  heroImageUrl?: T;
  heroImageAlt?: T;
  storyTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  placeholders?:
    | T
    | {
        label?: T;
        image?: T;
        imageUrl?: T;
        alt?: T;
        shape?: T;
        id?: T;
      };
  valuesEyebrow?: T;
  valuesTitle?: T;
  valuesIntro?: T;
  values?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaBody?: T;
  ctaLabel?: T;
  ctaHref?: T;
  ctaWhatsappLabel?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  contactLinkLabel?: T;
  cardCta?: T;
  nexoKicker?: T;
  nexoHeading?: T;
  nexoBody?: T;
  nexoCta?: T;
  serviceWhatsappCta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  environmentsHeading?: T;
  environmentsIntro?: T;
  contactCta?: T;
  mosaicContact?:
    | T
    | {
        title?: T;
        body?: T;
        cta?: T;
        href?: T;
      };
  mosaicWork?:
    | T
    | {
        title?: T;
        cta?: T;
        href?: T;
        fallbackTitle?: T;
        fallbackBody?: T;
        fallbackCta?: T;
      };
  projects?:
    | T
    | {
        title?: T;
        titleLines?:
          | T
          | {
              line?: T;
              id?: T;
            };
        caption?: T;
        isRealWork?: T;
        image?: T;
        imageUrl?: T;
        alt?: T;
        width?: T;
        height?: T;
        fit?: T;
        panels?:
          | T
          | {
              image?: T;
              src?: T;
              alt?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  otherServiceOption?: T;
  submitLabel?: T;
  submittingLabel?: T;
  successMessage?: T;
  consent?: T;
  nameLabel?: T;
  phoneLabel?: T;
  phoneHint?: T;
  emailLabel?: T;
  emailHint?: T;
  serviceLabel?: T;
  messageLabel?: T;
  namePlaceholder?: T;
  phonePlaceholder?: T;
  emailPlaceholder?: T;
  servicePlaceholder?: T;
  messagePlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}